'use strict';
const CFG={ACCESS_CODE:'fartsheetai',DAILY_LIMIT:12,COOLDOWN_SEC:30,MAX_WAIT_MS:{whole:300000,single:120000},BASE_URL:'https://api.b.ai/v1',MODEL:'qwen3.8-flash',MAXT:{summary:350,devices:450,vocab:400,connections:450,whole:1600},CHUNKS:[[1,11],[12,23],[24,35],[36,49]]};
const API_KEY='sk-1gtwh083q9kq8okm4zavisgx36htljhf';
function unlockOk(input){return String(input).trim().toLowerCase()===CFG.ACCESS_CODE;}
function makerOk(input){return String(input).trim()==='Clated231202';}
function authorLast(book){return String((book&&book.author)||'').trim().split(/\s+/).pop()||'Author';}
function citationTail(bk,pages){const al=authorLast(bk);const w=Array.isArray(pages)?pages:[1,10];const ex=Math.round((w[0]+w[1])/2);return ' QUOTE FORMAT (mandatory): every quoted sentence must be a real quoted sentence — straight double quotes around the exact words, immediately followed by a parenthetical citation: ('+al+' ##) where ## is a page number INSIDE this section\'s page window '+w[0]+'-'+w[1]+'. Example: "the right example sentence" ('+al+' '+ex+'). No quote may appear without this format.';}
function citationBlockWhole(bk,windows){const al=authorLast(bk);const W=windows||{};function ln(sec){const w=W[sec]||[1,10];return '- '+sec+' pages '+w[0]+'-'+w[1]+(sec==='summary'?' (no quotes — never put a citation in the summary)':', e.g. "example sentence" ('+al+' '+Math.round((w[0]+w[1])/2)+')');}return ' QUOTE FORMAT (mandatory): every quoted sentence needs straight double quotes + a parenthetical citation ('+al+' ##) where ## is INSIDE that section\'s window. Per-section windows:\n'+['summary','devices','vocab','connections'].map(ln).join('\n')+'. No quote may appear without this format.';}
function normalizeQuote(raw,authorLastStr,page){let q=String(raw==null?'':raw).replace(/\s+/g,' ').trim();const m=q.match(/\([^()]*\)\s*$/);const cite=m?m[0].trim():'('+String(authorLastStr||'Author')+' '+(page==null?1:page)+')';const body=(m?q.slice(0,q.length-m[0].length):q).trim().replace(/^[\u201c\u201d"']+|[\u201c\u201d"']+$/g,'').trim();if(!body)return '';return '"'+body+'" '+cite;}
function todayStr(now){const d=now?new Date(now):new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function sentenceCount(t){const m=String(t).trim().match(/[^.!?]+[.!?]+/g);return m?m.length:0;}
function usageAllowed(usage,nowMs,maker){const now=nowMs||Date.now();const u={day:todayStr(now),calls:0,lastCallTs:0};Object.assign(u,usage||{});if(u.day!==todayStr(now)){u.day=todayStr(now);u.calls=0;}if(!maker){if(u.calls>=CFG.DAILY_LIMIT)return{ok:false,reason:'limit',u:u};const wait=CFG.COOLDOWN_SEC*1000-(now-u.lastCallTs);if(wait>0)return{ok:false,reason:'cooldown',retrySec:Math.ceil(wait/1000),u:u};}return{ok:true,u:u};}
function parseSectionJSON(text){if(!text)return null;let t=String(text).trim();if(t.startsWith('```')){t=t.replace(/^```[a-zA-Z]*\n?/,'').replace(/\n?```\s*$/,'');}try{const o=JSON.parse(t);return(o&&typeof o==='object')?o:null;}catch(e){return null;}}
const CYCLE=['summary','devices','vocab','connections'];
const SHEET_PAGES=10;
function sectionForSheet(n){return CYCLE[(n-1)%4];}
function defaultPagesForSheet(n,startPage){const s=Number(startPage)>0?Number(startPage):1;return[s+SHEET_PAGES*(n-1),s+SHEET_PAGES*n-1];}
function sheetWindowsForSheet(n,startPage){const b=(Number(startPage)>0?Number(startPage):1)+40*(n-1);return{summary:[b,b+9],devices:[b+10,b+19],vocab:[b+20,b+29],connections:[b+30,b+39]};}
function isPublicAccess(a){return a==='public'||a==='public_scan';}
function nextIncompleteSheet(sheets,maxN){const s=sheets||{};for(let n=1;n<=maxN;n++){const e=s[String(n)];if(!e||!e.completed)return n;}return null;}
function cleanWikitext(w){let s=String(w==null?'':w);s=s.replace(/<ref[^>]*\/\s*>/gi,'').replace(/<ref[^>]*>[\s\S]*?<\/ref>/gi,'');for(let i=0;i<20&&s.indexOf('{{')>-1;i++){const prev=s;s=s.replace(/\{\{[^{}]*\}\}/g,'');if(s===prev)break;}s=s.replace(/\[\[[^\]]*\|([^\]]*)\]\]/g,'$1').replace(/\[\[([^\]]*)\]\]/g,'$1');s=s.replace(/\[[^\]]*\s([^\]]+)\]/g,'$1');s=s.replace(/'''/g,'').replace(/''/g,'');s=s.replace(/^=+\s*(.*?)\s*=+$/gm,'$1');s=s.replace(/<\/?(?:br|span|blockquote)[^>]*>/gi,'');s=s.replace(/\n{3,}/g,'\n\n');return s.trim();}
function extractPlotCharacters(wikitext){const lines=String(wikitext==null?'':wikitext).split('\n');function body(re){for(let i=0;i<lines.length;i++){if(re.test(lines[i].trim())){const out=[];for(let j=i+1;j<lines.length;j++){if(/^==(?!=)/.test(lines[j].trim()))break;out.push(lines[j]);}return out.join('\n');}}return'';}return{plot:cleanWikitext(body(/^={2,}\s*Plot\s*={2,}/i)),characters:cleanWikitext(body(/^={2,}\s*Characters?\b/i))};}
function sliceForWindow(fullText,totalPages,pages){if(!fullText||!pages)return'';const per=Math.max(fullText.length/Math.max(Number(totalPages)||0,1),1);const start=Math.max(0,Math.floor((pages[0]-1)*per)-1500);const end=Math.min(fullText.length,Math.ceil(pages[1]*per)+1500);return fullText.slice(start,end).slice(0,24000);}
const SECTION_RULES={summary:'Section: SUMMARY. JSON shape: {"summary":"one paragraph summarizing the main points of what happens in these pages, written in plain student voice without copying the author\'s prose, at least 5 sentences"}.',devices:'Section: LITERARY DEVICES. JSON shape: {"devices":[{"name":"device name","quote":"\"actual sentence\" (AuthorLastName page)","effect":"complete sentence: how this device affects the reader understanding, emotions, or engagement","mood":"complete sentence: how this device contributes to the mood or tone of the passage"}]} with exactly 2 entries using DIFFERENT devices chosen from: simile, metaphor, personification, onomatopoeia, hyperbole, alliteration, allusion, irony, foreshadowing, imagery.',vocab:'Section: VOCABULARY. JSON shape: {"words":[{"word":"a word from these pages that is new, funny, interesting, hard, uncommon, strange, or important","definition":"plain dictionary definition of the word","quote":"\"actual sentence\" (AuthorLastName page)"}]} with exactly 3 entries.',connections:'Section: CONNECTIONS. JSON shape: {"connections":[{"pages":"page number(s) inside the reading range","quote":"\"actual sentence\" (AuthorLastName page)","connection":"2 or more sentences, first person as a student: why the quote stood out, what you thought or felt reading it, and what it clarifies about the story, a character, a conflict, or a theme"}]} with exactly 2 entries.'};
function buildSystemPrompt(book,section,pages,grounding){const bk=book||{};const p=pages||defaultPagesForSheet(1);const g=grounding||{};const mode=g.mode||'none';const total=Number(bk.pages)||0;const window=total>0?'treat that window as ~'+Math.max(1,Math.round(100*p[0]/total))+'%-~'+Math.min(100,Math.round(100*p[1]/total))+"% of the book's story":'treat that window as early/middle/late relative to where pages '+p[0]+'-'+p[1]+' sit';const head='You are drafting ONE section of a classroom F.A.R.T. (Friends All Reading Together) sheet for "'+(bk.title||'Unknown')+'" by '+(bk.author||'unknown author')+'. This sheet covers ONLY pages '+p[0]+'-'+p[1]+' — '+window+'. Output ONLY one JSON object, no markdown, no commentary.';const rules=SECTION_RULES;let ground='';if(mode==='text'){ground='The ACTUAL BOOK TEXT for this window is provided below (OCR, some noise). Quote sentences VERBATIM from it (you may omit garbled chars, never invent a sentence not present). Words for VOCABULARY must appear in the slice. BOOK TEXT SLICE:\n'+String(g.slice||'');}else if(mode==='plot'){ground='GROUND TRUTH PLOT (Wikipedia) below — use ONLY characters, places, and events from it; place events plausibly inside the window by story proportion; keep invented-but-plausible quotes short (max 15 words) since the student must replace them with real sentences.'+(g.plot?'\nPLOT:\n'+g.plot:'')+(g.characters?'\nCHARACTERS:\n'+g.characters:'');}else{ground=" You cannot see the student's copy of the book, so this is a best-effort draft from general knowledge of the plot: never invent chapter names, keep quoted sentences short and plausible, and write complete self-contained sentences. The student must fix quotes against the sentences they actually read.";}return head+ground+' '+rules[section]+((section==='devices'||section==='vocab'||section==='connections')?citationTail(bk,p):'');}
function buildWholeSheetPrompt(book,windows,grounds){const bk=book||{};const w=windows||{};const g=grounds||{};const SECS=['summary','devices','vocab','connections'];const pg=function(s2){const q=w[s2];return Array.isArray(q)?q[0]+'-'+q[1]:'?';};const head='You are drafting the ENTIRE classroom F.A.R.T. (Friends All Reading Together) sheet for "'+(bk.title||'Unknown')+'" by '+(bk.author||'unknown author')+' in ONE reply: summary pages '+pg('summary')+', devices pages '+pg('devices')+', vocabulary pages '+pg('vocab')+', connections pages '+pg('connections')+'. Output ONE JSON object, no markdown, no commentary: {"summary":{"summary":"..."},"devices":{"devices":[...]},"vocab":{"words":[...]},"connections":{"connections":[...]}} - the value of each top-level key is that section\'s own JSON object.';let out=head;SECS.forEach(function(sec){const gg=g[sec]||{};if(gg.mode==='text'&&gg.slice){out+='\nWINDOW TEXT for '+sec+' (quote VERBATIM, OCR noise allowed, never invent): '+String(gg.slice).slice(0,10000);}});const anyNon=SECS.some(function(sec){return !g[sec]||g[sec].mode!=='text';});if(anyNon){const plotSec=SECS.filter(function(sec){return g[sec]&&g[sec].mode==='plot'&&g[sec].plot;})[0];const plot=plotSec?String(g[plotSec].plot).slice(0,12000):'';const chars=plotSec?String(g[plotSec].characters||''):'';out+='\nGROUND TRUTH PLOT (Wikipedia, shared across non-text sections):'+(plot?'\nPLOT:\n'+plot:'')+(chars?'\nCHARACTERS:\n'+chars:'');}out+='\nSection modes: '+SECS.map(function(sec){return 'section '+sec+' \u2192 mode '+(((g[sec]&&g[sec].mode)||'none'));}).join('; ')+'. Text-mode sections must quote VERBATIM from their WINDOW TEXT; plot/none modes are reconstructed: invented-but-plausible quotes max 15 words, the student must replace them with real sentences and fix page numbers; never invent chapter names; write complete self-contained sentences.';out+=citationBlockWhole(bk,w);out+='\n'+SECS.map(function(sec){return SECTION_RULES[sec];}).join('\n');return out;}
function buildUserPrompt(book,section,pages){const bk=book||{};let s='Write the '+section+' section for "'+(bk.title||'Unknown')+'"';if(pages)s+=', pages '+pages[0]+'-'+pages[1]+' of the reading window';return s+'. One JSON object only.';}
